add support for checking agent not running implements #340

diff --git a/nagios/check_puppet_agent b/nagios/check_puppet_agent
--- a/nagios/check_puppet_agent
+++ b/nagios/check_puppet_agent
@@ -38,65 +38,84 @@
 # 20120214  trey85stang Modified, added getopts, usage, defaults
 # 20120220  A.Swen      Statefile can be overriden
 
+THIS_FILE=`readlink -f "$0"`
+PROGNAME=`basename "$THIS_FILE"`
+PROGPATH=`dirname "$THIS_FILE"`
+
+. $PROGPATH/utils.sh || exit 3
+
 # SETTINGS
 CRIT=7200
 WARN=3600
 statedir='/var/lib/puppet/state'
 statefile='/var/lib/puppet/state/last_run_summary.yaml'
+pidfile='/var/run/puppet/agent.pid'
 use_sudo=1
+RUNNING=1
 
 # FUNCTIONS
 result () {
   case $1 in
-    0) echo "OK: Puppet agent ${version} running catalog version ${config}";rc=0 ;;
-    1) echo "WARNING: last_run_summary.yaml not found or incomplete";rc=1 ;;
-    2) echo "WARNING: Last run was ${time_since_last} seconds ago. warn is ${WARN}";rc=1 ;;
-    3) echo "CRITICAL: Last run was ${time_since_last} seconds ago. crit is ${CRIT}";rc=2 ;;
-    4) echo "CRITICAL: Puppet daemon not running";rc=2 ;;
-    5) echo "UNKNOWN: no WARN or CRIT parameters were sent to this check";rc=3 ;;
-    6) echo "CRITICAL: Last run had 1 or more errors. Check the logs";rc=2 ;;
-    7) echo "OK: Puppet agent ${version} running";rc=0 ;;
-    8) echo "WARNING: Running obsolute puppet agent version ${version}. current is ${REQVER}";rc=1 ;;
-    9) echo "WARNING: last_run_summary.yaml not readable";rc=1 ;;
+    0) echo "OK: Puppet agent ${version} running, catalog version ${config_str}"; exit $STATE_OK;;
+    1) echo "WARNING: last_run_summary.yaml not found or incomplete"; exit $STATE_WARNING;;
+    2) echo "WARNING: Last run at ${last_run_str} was ${time_since_last} seconds ago. warn is ${WARN}"; exit $STATE_WARNING;;
+    3) echo "CRITICAL: Last run  ${last_run_str} was ${time_since_last} seconds ago. crit is ${CRIT}"; exit $STATE_CRITICAL;;
+    4) echo "CRITICAL: Puppet daemon not running"; exit $STATE_CRITICAL;;
+    5) echo "UNKNOWN: no WARN or CRIT parameters were sent to this check"; exit $STATE_UNKNOWN;;
+    6) echo "CRITICAL: Last run had 1 or more errors. Check the logs"; exit $STATE_CRITICAL;;
+    7) echo "OK: Puppet agent ${version} running"; exit $STATE_OK;;
+    8) echo "WARNING: Running obsolute puppet agent version ${version}. current is ${REQVER}"; exit $STATE_WARNING;;
+    9) echo "WARNING: last_run_summary.yaml not readable"; exit $STATE_WARNING;;
+    10) echo "OK: Puppet agent not running"; exit $STATE_OK;;
+    11) echo "CRITICAL: Puppet agent is running, but should not be running"; exit $STATE_CRITICAL;;
   esac
-  exit $rc
+  exit $STATE_UNKNOWN
 }
 
 usage () {
   echo ""
   echo "USAGE: "
-  echo "  $0 [-w 3600] [-c 7200] [-s statefile]"
-  echo "    -w warning threshold (default 3600 seconds)"
-  echo "    -c ciritcal threshold (default 7200 seconds)"
-  echo "    -s statefile (default: /var/lib/puppet/state/last_run_summary.yaml)"
-  echo "    -v required version number, if an agent with a lower version number"
-  echo "       is detected a warning will be generated"
+  echo "  $PROGNAME [-w seconds] [-c seconds] [-s statefile] [-v versionno] [-r 0|1]"
+  echo "    -w        warning threshold (default $WARN seconds)"
+  echo "    -c        ciritcal threshold (default $CRIT seconds)"
+  echo "    -s        statefile (default: $statefile)"
+  echo "    -v        required version number, if an agent with a lower version number"
+  echo "              is detected a warning will be generated"
+  echo "    -r <0|1>  if 1 check if agent is running (default), if 0 verify agent is not running"
   echo ""
   exit 1
 }
 
-while getopts "c:s:w:v:" opt
+while getopts "c:s:w:v:r:" opt
 do
   case $opt in
     c)
-      if ! echo $OPTARG | grep -q "[A-Za-z]" && [ -n "$OPTARG" ]
-      then
+      if ! echo $OPTARG | grep -q "[A-Za-z]" && [ -n "$OPTARG" ]; then
         CRIT=$OPTARG
       else
+		echo "invalid value $OPTARG for $opt"
         usage
       fi
     ;;
     s) statefile=${OPTARG} ;;
     w)
-      if ! echo $OPTARG | grep -q "[A-Za-z]" && [ -n "$OPTARG" ]
-      then
+      if ! echo $OPTARG | grep -q "[A-Za-z]" && [ -n "$OPTARG" ]; then
         WARN=$OPTARG
       else
+		echo "invalid value $OPTARG for $opt"
         usage
       fi
     ;;
     v)
       REQVER=$OPTARG
+    ;;
+    r)
+      if echo $OPTARG | grep -q "[01]" && [ -n "$OPTARG" ]; then
+        RUNNING=$OPTARG
+      else
+		echo "invalid value $OPTARG for $opt"
+        usage
+      fi
     ;;
     *)
       usage
@@ -105,8 +124,21 @@ do
 done
 
 # check puppet daemon:
-# I only know the cmd lines for Debian and CentOS/RedHat:
-[ "$(ps aux | grep "[p]uppet agent")" ] || result 4
+if [ $RUNNING -eq 0 ]; then
+	[ ! -f $pidfile ] && result 10
+	pid=`cat $pidfile`
+	kill -0 &>1 > /dev/null $pid && result 11
+	result 10
+else
+	[ ! -f $pidfile ] && result 4
+	pid=`cat $pidfile`
+	if kill -0 &>1 > /dev/null $pid; then
+		# agent is running, so let's continue with the next tests
+		true
+	else
+		result 4
+	fi
+fi
 
 # check version
 version=$(puppet --version)
@@ -145,6 +177,7 @@ now=$(date +%s)
 time_since_last=$((now-last_run))
 [ ${time_since_last} -ge ${CRIT} ] && result 3
 [ ${time_since_last} -ge ${WARN} ] && result 2
+last_run_str=`date --rfc-2822 --date "@$last_run"`
 
 # get some more info from the yaml file
 config=`echo "$last_run_summary" | awk -F': ' '/config:/ { print $2 }'`
@@ -154,6 +187,8 @@ failed_to_restart=`echo "$last_run_summary" | awk -F': ' '/failed_to_restart:/ {
 
 [ -z "${last_run}" -o -z "${config}" -o -z "${version}" -o -z "${failed}" -o -z "${failure}" -o -z "${failed_to_restart}" ] && result 1
 [ ${failed} -gt 0 -o  ${failure} -gt 0 -o ${failed_to_restart} -gt 0 ] && result 6
+
+config_str=`date --rfc-2822 --date "@$config"`
 
 # if we come here it works!
 result 0
