improve openvpn zip config script
git-svn-id: file:///local/nuna/developer/svn/syscfg@983 dafa5faa-33fa-417a-9101-543bec8d0801

diff --git a/openvpn/openvpn-zip-config b/openvpn/openvpn-zip-config
--- a/openvpn/openvpn-zip-config
+++ b/openvpn/openvpn-zip-config
@@ -1,7 +1,7 @@
 #!/bin/bash
 verbose=1
 files=''
-outfile=''
+outdir=''
 CONFIG_DIR='/etc/openvpn'
 PUPPET_OPENVPN_DIR='/var/lib/puppet/modules/openvpn'
 
@@ -10,10 +10,16 @@ function usage()
 	echo "openvpn-zip-config [OPTIONS] <files>"
 	echo "    -h, --help      shows this help screen"
 	echo "    -v,--verbose    verbose output"
-	echo "    -o, --outfile   name of the output file"
+	echo "    -o, --outdir    name of the output directory"
 	echo "    -b, --basedir   name of the base directory (default: outfiledir)"
 	echo "    --configdir     name of the openvpn config directory (default: $CONFIG_DIR)"
 	exit 0
+}
+
+function verbose_exec()
+{
+	[ $verbose -ne 0 ] && echo "$@"
+	"$@"
 }
 
 function zip_config()
@@ -54,8 +60,8 @@ function zip_config()
 		esac
 	fi
 	[ $verbose -ne 0 ] && echo "config_file=$config_file"
-	name=`awk '/^#[ ]*(name)[ ]+.*$/ { print $3; }' < "$config_file"`
-	ostype=`awk '/^#[ ]*(ostype)[ ]+.*$/ { print $3; }' < "$config_file"`
+	name=`awk '/^#[ ]*(name)[ ]+.*$/ { print $3; }' "$config_file"`
+	ostype=`awk '/^#[ ]*(ostype)[ ]+.*$/ { print $3; }' "$config_file"`
 	
 	if [ -z "$name" ]; then
 		name="$fallback_name"
@@ -64,30 +70,30 @@ function zip_config()
 	fi
 	[ -z "$ostype" ] && ostype="$fallback_ostype"
 
-	[ $verbose -ne 0 ] && echo "compress $name ($config_file, $config_dir/*) to $outfile"
+	[ $verbose -ne 0 ] && echo "compress $name ($ostype, $config_file, $config_dir/*) to $outfile"
 
 	num_errors=0
 	zipdir=`mktemp -d /tmp/openvpn_zip.XXXXXX`
 	case "$ostype" in
 		'linux')
-			cp -p "$config_file" "$zipdir/$name.conf"
-			mkdir "$zipdir/$name"
+			verbose_exec cp -p "$config_file" "$zipdir/$name.conf"
+			verbose_exec mkdir "$zipdir/$name"
 			pem_files=`ls -1 "$config_dir"/*.{crt,pem} 2>/dev/null`
 			for f in $pem_files; do
 				if [ -r "$f" ]; then
-					cp -p "$f" "$zipdir/$name"
+					verbose_exec cp -p "$f" "$zipdir/$name"
 				else
 					echo "Cannot read $f"
 					(( num_errors++ ))
 				fi
 			done
 			;;
-		'win'|'android')
-			cp -p "$config_file" "$zipdir/$name.ovpn"
+		'win'|'android'|'windows')
+			verbose_exec cp -p "$config_file" "$zipdir/$name.ovpn"
 			pem_files=`ls -1 "$config_dir"/*.{crt,pem} 2>/dev/null`
 			for f in $pem_files; do
 				if [ -r "$f" ]; then
-					cp -p "$f" "$zipdir"
+					verbose_exec cp -p "$f" "$zipdir"
 				else
 					echo "Cannot read $f" >&2
 					(( num_errors++ ))
@@ -95,6 +101,7 @@ function zip_config()
 			done
 			;;
 		*)
+			[ $verbose -ne 0 ] && echo "unhandled ostype $ostype"
 			;;
 	esac
 
@@ -109,9 +116,9 @@ function zip_config()
 	[ $verbose -ne 0 ] && echo "use base directory $zipdir"
 	# goto the temp directory to create the relative path inside the zip
 	pushd "$zipdir" > /dev/null
-	[ $verbose -ne 0 ] && echo /usr/bin/zip -r "$outfile" $files_fixed_names
+	[ $verbose -ne 0 ] && echo /usr/bin/zip -r "$outfile" . -i *
 	# TODO: need to pass --encrypt
-	msg=`/usr/bin/zip -q -r "$outfile" * 2>&1`
+	msg=`/usr/bin/zip -q -r "$outfile" . -i * 2>&1`
 	RES=$?
 	popd > /dev/null
 
@@ -131,7 +138,15 @@ function generate_client_config()
 	name="$1"
 	config_file="$2"
 	config_dir="$3"
+	outdir="$4"
 	clients_file="$PUPPET_OPENVPN_DIR/${name}_clients"
+	
+	if [ ! -r "$clients_file" ]; then
+		echo "Cannot read client list from $clients_file" >&2
+		return 1
+	fi
+	
+	client_zip_basename="$outdir/$(basename "$config_dir")"
 
 	puplic_address=`awk '/^#[ ]*(public-address)[ ]+.*$/ { print $3; }' "$config_file"`
 	puplic_port=`awk '/^#[ ]*(public-port)[ ]+.*$/ { print $3; }' "$config_file"`
@@ -167,7 +182,7 @@ function generate_client_config()
 				config_ext='conf'
 				client_file_dir="/etc/openvpn/${clientname}/"
 				;;
-			'win')
+			'win'|'windows')
 				status_line="# status ${clientname}-status.log"
 				log_append_line="# log-append ${clientname}.log"
 				config_ext='ovpn'
@@ -234,7 +249,7 @@ function generate_client_config()
 		cat > "$client_configdir/${clientname}.${config_ext}" <<CONFEOF
 #
 # THIS FILE IS AUTOMATICALLY GENERATED BY
-# AR SOFT PUPPET CONFIG
+# openvpn-zip-config
 #
 # name $clientname
 # ostype $clientostype
@@ -269,33 +284,35 @@ $routes
 #
 CONFEOF
 		cat "$client_configdir/${clientname}.${config_ext}"
-		client_zipfile="$config_dir/${clientname}.zip"
+		client_zipfile="${client_zip_basename}_${clientname}.zip"
 
 		# use the config directory of the server (for certs)
 		zip_config "client" "$client_configdir/${clientname}.${config_ext}" "$client_configdir" "$client_zipfile"
 		rm -rf "$client_configdir"
 	done < "$clients_file"
+	return 0
 }
 
 function handle_config()
 {
 	name="$1"
 	config_file="$2"
+	outdir="$3"
 	if [ -e "$config_file" ]; then
 		config_dir="${config_file%%.conf}"
-		config_zip="${config_file%%.conf}.zip"
+		config_zip="$outdir/$(basename "$config_dir").zip"
 		[ $verbose -ne 0 ] && echo "handle_config name=${name}"
 		[ $verbose -ne 0 ] && echo "handle_config config_file=${config_file}"
 		[ $verbose -ne 0 ] && echo "handle_config config_dir=${config_dir}"
+		[ $verbose -ne 0 ] && echo "handle_config config_zip=${config_zip}"
 		type=`awk '/^(server[ ]+.*|client[ ]*)$/ { print $1; }' "$config_file"`
 		if [ "$type" == "client" ]; then
 			[ $verbose -ne 0 ] && echo "client config"
 			zip_config "client" "$config_file" "$config_dir" "$config_zip"
 		elif [ "$type" == "server" ]; then
 			[ $verbose -ne 0 ] && echo "server config"
-			server_zip="${config_file%%.conf}.zip"
 			zip_config "server" "$config_file" "$config_dir" "$config_zip"
-			generate_client_config "$name" "$config_file" "$config_dir"
+			generate_client_config "$name" "$config_file" "$config_dir" "$outdir"
 #			if [ -d "$config_dir/clients" ]; then
 #				for CLIENTCONFIG in "$config_dir/clients"/*; do
 #					if [ -d "$CLIENTCONFIG" ]; then
@@ -316,7 +333,7 @@ while [ $# -ne 0 ]; do
 	case "$1" in
 		"-?"|"-h"|"--help") usage;;
 		"-v"|"--verbose") verbose=1; ;;
-		"-o"|"--outfile") outfile="$2"; shift ;;
+		"-o"|"--outdir") outdir="$2"; shift ;;
 		"-b"|"--basedir") basedir="$2"; shift ;;
 		"-t"|"--topdir") topdir="$2"; shift ;;
 		*)
@@ -330,8 +347,15 @@ while [ $# -ne 0 ]; do
 	shift
 done
 
+[ -z "$outdir" ] && outdir=`pwd`
+
 if [ ! -d "$CONFIG_DIR" ]; then
 	echo "OpenVPN is not installed. Please install openvpn first." >&2
+	exit 1
+fi
+
+if [ ! -d "$outdir" ]; then
+	echo "Output directory $outdir does not exist." >&2
 	exit 1
 fi
 
@@ -339,11 +363,11 @@ if [ -z "$selected_configs" ]; then
 	for CONFIG in $CONFIG_DIR/*.conf; do
 		tmp=`basename $CONFIG`
 		name=${tmp%%.conf}
-		handle_config "$name" "$CONFIG"
+		handle_config "$name" "$CONFIG" "$outdir"
 	done
 else
 	for NAME in $selected_configs; do
-		handle_config "$NAME" "$CONFIG_DIR/$NAME.conf"
+		handle_config "$NAME" "$CONFIG_DIR/$NAME.conf" "$outdir"
 	done
 fi
 
