cleanup scripts re-implement slapd-backup
git-svn-id: file:///local/nuna/developer/svn/syscfg@1051 dafa5faa-33fa-417a-9101-543bec8d0801

diff --git a/ldap/nsswitch-ldap b/ldap/nsswitch-ldap
--- a/ldap/nsswitch-ldap
+++ b/ldap/nsswitch-ldap
@@ -28,7 +28,7 @@ nsswitch_ldap_modify() {
 	if [ $RES -eq 0 ]; then
 		mv "$tmp" "$NSSWITCH_CONF"
 	else
-		echo "Failed to modify $NSSWITCH_CONF"
+		echo "Failed to modify $NSSWITCH_CONF" 1>&2
 	fi
 }
 
@@ -48,7 +48,7 @@ while [ $# -ne 0 ]; do
 		"-?"|"-h"|"--help") usage;;
 		"enable"|"disable") action="$1"; ;;
 		*)
-			echo "Unknown parameter $1"
+			echo "Unknown parameter $1" 1>&2
 			exit 1
 		;;
 	esac
@@ -56,7 +56,7 @@ while [ $# -ne 0 ]; do
 done
 
 if [ -z "$action" ]; then
-	echo "Neither 'enable' nor 'disable' is specified.'"
+	echo "Neither 'enable' nor 'disable' is specified.'" 1>&2
 	exit 1
 else
 	case "$action" in
