clean up script and add import host functionality (untested)

diff --git a/bind/dns-update b/bind/dns-update
--- a/bind/dns-update
+++ b/bind/dns-update
@@ -2,6 +2,7 @@
 
 nsupdate_bin=`which nsupdate`
 verbose=0
+noop=0
 commands=''
 nsupdate_opts=''
 nsupdate_key=''
@@ -21,40 +22,72 @@ function usage()
 	echo "    -a,--add <dnsname> <ipaddr>     adds the given DNS A record"
 	echo "    -d,--delete <dnsname>           deletes the specified DNS A record"
 	echo "    -u,--update <dnsname> <ipaddr>  adds the given DNS A record"
+	echo "    --update-host <hostname> <addr> updates the given host for the specified address."
+	echo "    --import-host <hostname> <dnsserver>"
+	echo "                                    import the result from the specified DNS server and update the"
+	echo "                                    local DNS server."
 	exit 0
 }
 
-server localhost
-key vpnupdate $DNSKEY
 function reverse_ipv4 {
 	echo $1 | nawk -F. '{print $4"."$3"."$2"."$1}'
 }
 
+if [ -z "$nsupdate_bin" ]; then
+	echo "nsupdate is not available. Please install dnsutils." >&2
+	exit 1
+fi
+
+command_file=`mktemp`
 # parse command line arguments
 while [ $# -ne 0 ]; do
 	case "$1" in
 		"-?"|"-h"|"--help") usage;;
 		"-v"|"--verbose") verbose=1; nsupdate_opts="$nsupdate_opts -d"; ;;
-		"-a"|"--add") 
-			commands="${commands}update add $2 $ttl $rrtype $3\n"
+		'--noop') noop=1; ;;
+		"-a"|"--add")
+			echo "update add $2 $ttl $rrtype $3" >> "$command_file"
 			shift; shift;
 			;;
 		"-d"|"--delete") 
-			commands="${commands}update delete $2 $rrtype\n"
+			echo "update delete $2 $rrtype" >> "$command_file"
 			;;
 		"-u"|"--update") 
-			commands="${commands}update delete $2 $rrtype\n"
-			commands="${commands}update add $2 $ttl $rrtype $3\n"
+			echo "update delete $2 $rrtype" >> "$command_file"
+			echo "update add $2 $ttl $rrtype $3" >> "$command_file"
 			shift; shift;
 			;;
 		"--update-host")
 			hostname="$2"
 			addr="$3"
 			revaddr=`reverse_ipv4 "$addr"`
-			commands="${commands}update delete $revaddr.in-addr.arpa.\n"
-			commands="${commands}update delete $hostname.\n"
-			commands="${commands}update add $hostname. $ttl IN A $addr\n"
-			commands="${commands}update add $revaddr.in-addr.arpa. $ttl PTR $hostname.\n"
+			echo "update delete $revaddr.in-addr.arpa." >> "$command_file"
+			echo "update delete $hostname." >> "$command_file"
+			echo "update add $hostname. $ttl IN A $addr" >> "$command_file"
+			echo "update add $revaddr.in-addr.arpa. $ttl PTR $hostname." >> "$command_file"
+			shift; shift;
+			;;
+		'--import-host'|'--import')
+			hostname="$2"
+			anotherserver="$3"
+			if [ -z "$anotherserver" ]; then
+				echo "No DNS server to query specified." >&2
+				exit 1
+			fi
+			addresses=`dig +short "$hostname" "@$anotherserver" 2>&1`; RES=$?
+			if [ $RES -ne 0 ]; then
+				echo "Error while retrieving address of $hostname on $anotherserver" >&2
+			elif [ -z "$addresses" ]; then
+				echo "No record for $hostname on $anotherserver" >&2
+			else
+				echo "update delete $hostname." >> "$command_file"
+				for addr in $addresses; do
+					revaddr=`reverse_ipv4 "$addr"`
+					echo "update delete $revaddr.in-addr.arpa." >> "$command_file"
+					echo "update add $hostname. $ttl IN A $addr" >> "$command_file"
+					echo "update add $revaddr.in-addr.arpa. $ttl PTR $hostname." >> "$command_file"
+				done
+			fi
 			shift; shift;
 			;;
 		"-k","--key") 
@@ -74,24 +107,28 @@ while [ $# -ne 0 ]; do
 			shift
 			;;
 		*)
-			if [ ! -z "$message" ]; then
-				message="$message $1"
-			else
-				message="$1"
-			fi
+			echo "unrecognized argument $1" >&2
+			exit 1
 		;;
 	esac
 	shift
 done
 
-if [ -z "$commands" ]; then
-	echo "No commands specified."
+if [ ! -s "$command_file" ]; then
+	echo "No commands specified." >&2
+	exit 1
 else
 	# prepend the server command and append the send command
 	commands="server $server\n${commands}send\n"
 	if [ ! -z "$nsupdate_key" ]; then
 		nsupdate_opts="$nsupdate_opts -k $nsupdate_key"
 	fi
-	echo -e "$commands" | "$nsupdate_bin" $nsupdate_opts
+	if [ $noop -eq 0 ]; then
+		[ $verbose -ne 0 ] && echo "cat \"$command_file\" | \"$nsupdate_bin\" $nsupdate_opts"
+		cat "$command_file" | "$nsupdate_bin" $nsupdate_opts
+	else
+		cat "$command_file"
+	fi
 fi
 
+rm -f "$command_file"
