latest fixes from fast

diff --git a/trac/trac-backup b/trac/trac-backup
--- a/trac/trac-backup
+++ b/trac/trac-backup
@@ -12,39 +12,46 @@ QUIET=0
 [ ! -d "$LATEST_BACKUP_DIR" ] && mkdir -p "$LATEST_BACKUP_DIR"
 
 # parse command line arguments
-while [ $# -ne 0 ]; do        
-	case "$1" in          
-	"-?") usage;; 
-	"-h") usage;; 
-	"--help") usage;;
+while [ $# -ne 0 ]; do
+	case "$1" in
+	'-?'|'-h'|'--help') usage;; 
 	"-q"|"--quiet") QUIET=1 ;;
-	*)                         
-		TRACS=$1 
-	;;                                      
-	esac                                    
-	shift                                   
-done                                            
- 
+	*)
+		TRACS="$TRACS $1"
+	;;
+	esac
+	shift
+done
+
 function usage() {
 	echo "usage: tracbackup [-q|--quiet] [repo]"
 	exit 1
 }
 
 function tracdump() {
-    TRAC=$1
-    BAKFILE=$2
+	TRAC=$1
+	BAKFILE=$2
 
 	TMPDIR=`mktemp -d /tmp/tracXXXXXX`
 	BAKDIR=$TMPDIR/`basename $TRAC`
-    echo -n "Backup $TRAC to $BAKFILE (using $BAKDIR)"
-    msg=`trac-admin $TRAC hotcopy 2>&1 > /dev/null $BAKDIR && tar cfj $BAKFILE $BAKDIR 2>&1 && rm -rf $TMPDIR`
-    RES=$?
-    if [ $RES -eq 0 ]; then
-		echo "[done]"
-    else
-        echo "[failed]"
-    fi
-    return $RES
+	echo -n "Backup $TRAC to $BAKFILE (using $BAKDIR)"
+	msg=`trac-admin "$TRAC" hotcopy 2>&1 $BAKDIR --no-database`
+	RES=$?
+	if [ $RES -eq 0 ]; then
+		msg=`tar cfj "$BAKFILE" "$BAKDIR" 2>&1`
+		RES=$?
+		if [ $RES -eq 0 ]; then
+				echo "[done]"
+		else
+				echo " [compress failed]"
+				echo "$msg"
+		fi
+	else
+		echo " [failed]"
+		echo "$msg"
+	fi
+	rm -rf "$TMPDIR"
+	return $RES
 }
 
 [ ! -d "$BACKUPDIR" ] && mkdir -p "$BACKUPDIR"
@@ -52,23 +59,24 @@ function tracdump() {
 
 for r in $TRACS; do
 	if [ ! -d $r ]; then
-		echo "trac installation $r not available"
-		continue
+			echo "trac installation $r not available"
+			continue
 	fi
 
-    name=`basename $r`
+	name=`basename $r`
 	BAKFILE=$BACKUPDIR/trac_${name}_`date +%Y%m%d`.bz2
-	dumpmsg=`tracdump $r $BAKFILE`
-	if [ $? -eq 0 ]; then
+	tracdump "$r" "$BAKFILE"; RES=$?
+	if [ $RES -eq 0 ]; then
 		putmsg=`putremote $BAKFILE && remove_oldest "trac_${name}_*"`
 		if [ $? -ne 0 ]; then
 			echo "$dumpmsg"
 			echo "$putmsg"
 		fi
-	else
-		echo "$dumpmsg"
-	fi
 
-	cp "$BAKFILE" "$LATEST_BACKUP_DIR/fast-srv01_trac_${name}.tar.bz2"
+		cp "$BAKFILE" "$LATEST_BACKUP_DIR/fast-srv01_trac_${name}.tar.bz2" || echo "failed to copy backup file"
+	else
+		echo "trac dump failed with error $RES"
+		[ -f "$BAKFILE" ] && rm -f "$BAKFILE"
+	fi
 done
 
