improve repo path handling

diff --git a/scm/git-subdir2submodule b/scm/git-subdir2submodule
--- a/scm/git-subdir2submodule
+++ b/scm/git-subdir2submodule
@@ -7,7 +7,6 @@ repo_git=''
 repo_schema=''
 subdir_list=''
 outdir=''
-submodule_base_url=''
 force=0
 config_file=''
 subdir_num=0
@@ -31,7 +30,6 @@ function usage()
     echo "    --init             initialize submodules in main GIT repository."
     echo "    --add              add submodules to main GIT repository."
     echo "    -o <dir>           specifies the output directory"
-    echo "    -s <base_url>      override the base url for submodules."
     echo "    --file <path>      text file which contains the submodule specifications."
     exit 0
 }
@@ -45,6 +43,21 @@ function verbose_exec()
 function cleanup_repo()
 {
 	true
+}
+
+function relative_path()
+{
+	local source="$1"
+	local target="$2"
+
+	local common_part=$source
+	local back=
+	while [ "${target#$common_part}" = "${target}" ]; do
+		common_part=$(dirname $common_part)
+		back="../${back}"
+	done
+
+	echo "${back}${target#$common_part/}"
 }
 
 function git_shrink()
@@ -115,7 +128,6 @@ function subdir_to_submodule()
 	local repodir="$1"
 	local subdir="$2"
 	local destdir="$3"
-	local public_url="$4"
 	if [ -d "$destdir" ]; then
 		if [ $force -eq 0 ]; then
 			if [ $keep -ne 0 ]; then
@@ -150,16 +162,7 @@ function subdir_to_submodule()
 			if [ $RES -eq 0 ]; then
 				git_shrink "$subdir_git_dir"; RES=$?
 				if [ $RES -eq 0 ]; then
-					if [ $submodule_add_origin -ne 0 ]; then
-						git remote add origin "$public_url"; RES=$?
-						if [ $RES -eq 0 ]; then
-							echo "Subdirectory successfully converted into $subdir_git_dir."
-						else
-							echo "Failed to add remote origin $public_url for GIT repository $subdir_git_dir." >&2
-						fi
-					else
-						echo "Subdirectory successfully converted into $subdir_git_dir."
-					fi
+					echo "Subdirectory successfully converted into $subdir_git_dir."
 				else
 					echo "Failed to reduce size of GIT repository $subdir_git_dir." >&2
 				fi
@@ -249,22 +252,22 @@ function fully_remove_subdir()
 function add_submodule()
 {
 	local repodir="$1"
-	local subdir="$2"
-	local submodule="$3"
+	local path="$2"
+	local submodule_repo="$3"
 	
 	pushd "$repodir" > /dev/null
 
-	git submodule add --force "$submodule" "$subdir"; RES=$?
+	git submodule add --force "$submodule_repo" "$path"; RES=$?
 	if [ $RES -eq 0 ]; then
 		# stash the modified .gitmodules
 		git add "${repodir}/.gitmodules"; RES=$?
 		if [ $RES -eq 0 ]; then
-			echo "Submodule $submodule as $subdir successfully added."
+			echo "Submodule $submodule_repo as $path successfully added."
 		else
 			echo "Failed to add ${repodir}/.gitmodules" >&2
 		fi
 	else
-		echo "Failed to add submodule $subdir as $submodule." >&2
+		echo "Failed to add submodule $subdir as $submodule_repo." >&2
 	fi
 
 	popd > /dev/null
@@ -281,7 +284,6 @@ while [ $# -ne 0 ]; do
 		'--add') submodule_add=1; ;;
 		'--init') submodule_add=1; submodule_init=1; ;;
 		'-o') outdir="$2"; shift; ;;
-		'-s') submodule_base_url="$2"; shift; ;;
 		'--file') config_file="$2"; shift; ;;
 		-*)
 			echo "Invalid option $1 specified." >&2
@@ -320,7 +322,6 @@ else
 fi
 
 [ -z "$outdir" ] && outdir=`readlink -f $(pwd)`
-[ -z "$submodule_base_url" ] && submodule_base_url=`dirname "$repo_git"`
 
 if [ ! -z "$config_file" ]; then
 	subdir_num=0
@@ -328,17 +329,16 @@ if [ ! -z "$config_file" ]; then
 	while IFS=$'\t ' read -r -a fields; do
 		[ ${#fields[*]} -eq 0 -o "${fields[0]:0:1}" == "#" ] && continue
 		
-		if [ ${#fields[*]} -lt 3 ]; then
-			echo "skip unrecognized line: $fields" 1>&2
-			continue
-		fi
-
 		subdir="${fields[0]}"
-		subdir_name="${fields[1]}"
-		subdir_repo_public="${fields[2]}"
-		
-		subdir_safe=${subdir_name//\//_}
-		subdir_git_dir="$outdir/${subdir_safe}.git"
+
+		subdir_safe=${subdir//\//_}
+
+		[ ${#fields[*]} -gt 1 ] && subdir_name="${fields[1]}" || subdir_name="$subdir_safe"
+		subdir_name_safe=${subdir_name//\//_}
+		[ $clone_bare -ne 0 ] && subdir_git_dir="$outdir/${subdir_name_safe}.git" || subdir_git_dir="$outdir/${subdir_name_safe}"
+		echo "subdir_git_dir=$subdir_git_dir"
+
+		[ ${#fields[*]} -gt 2 ] && subdir_repo_public="${fields[2]}" || subdir_repo_public="$subdir_git_dir"
 
 		subdir_array[$subdir_num]="$subdir"
 		subdir_converted_array[$subdir_num]=0
@@ -360,7 +360,7 @@ else
 		subdir_num=0
 		for subdir in $subdir_list; do
 			subdir_safe=${subdir//\//_}
-			subdir_git_dir="$outdir/${subdir_safe}.git"
+			[ $clone_bare -ne 0 ] && subdir_git_dir="$outdir/${subdir_safe}.git" || subdir_git_dir="$outdir/${subdir_safe}"
 		
 			subdir_array[$subdir_num]="$subdir"
 			subdir_converted_array[$subdir_num]=0
@@ -373,15 +373,16 @@ else
 
 fi
 
-repo_name=`basename "$repo_git"`
+repo_name=`basename "$repo_git" '.git'`
+cloned_git_dir="$outdir/${repo_name}.git"
 
 echo "GIT repository: $repo_git"
 echo "GIT repository name: $repo_name"
 echo "Output directory: $outdir"
-echo "Subdirectory list: $subdir_list"
-echo "Submodule base url: $submodule_base_url"
+echo "Subdirectory config: $config_file"
+echo "Main repository: $cloned_git_dir"
 
-if [ $verbose -ne 0 ]; then
+if [ $verbose -ne 0 -o 1 ]; then
 	for ((idx=0; idx < $subdir_num ; idx++)); do
 		subdir=${subdir_array[$idx]}
 		subdir_name=${subdir_name_array[$idx]}
@@ -391,15 +392,19 @@ if [ $verbose -ne 0 ]; then
 		echo "subdir name: $subdir_name"
 		echo "subdir repo: $subdir_repo"
 		echo "subdir repo public: $subdir_repo_public"
+		
+		rel_path=$(relative_path $cloned_git_dir $subdir_repo)
+		echo "subdir rel repo: $rel_path"
 	done
 fi
 
-cloned_git_dir="$outdir/${repo_name}.git"
 if [ $submodule_add -eq 0 ]; then
 	[ $clone_bare -ne 0 ] && bare_opt='--bare' || bare_opt=''
 else
 	bare_opt=''
 fi
+
+exit 0
 
 if [ $keep -ne 0 ]; then
 	if [ -d "$cloned_git_dir" ]; then
@@ -422,9 +427,8 @@ if [ $RES -eq 0 ]; then
 		subdir=${subdir_array[$idx]}
 		subdir_name=${subdir_name_array[$idx]}
 		subdir_repo=${subdir_repo_array[$idx]}
-		subdir_repo_public=${subdir_repo_public_array[$idx]}
 
-		subdir_to_submodule "$temp_git_dir" "$subdir" "$subdir_repo" "$subdir_repo_public"; RES=$?
+		subdir_to_submodule "$temp_git_dir" "$subdir" "$subdir_repo"; RES=$?
 		if [ $RES -eq 0 ]; then
 			echo "GIT repository for $subdir successfully created."
 		else
@@ -463,13 +467,13 @@ if [ $RES -eq 0 ]; then
 			for ((idx=0; idx < $subdir_num ; idx++)); do
 				subdir=${subdir_array[$idx]}
 				subdir_name=${subdir_name_array[$idx]}
-				subdir_repo_public=${subdir_repo_public_array[$idx]}
+				subdir_repo=${subdir_repo_array[$idx]}
 
-				add_submodule "$temp_git_dir" "$subdir" "$subdir_repo_public"; RES=$?
+				add_submodule "$temp_git_dir" "$subdir" "$subdir_repo"; RES=$?
 				if [ $RES -eq 0 ]; then
 					echo "Submodule $subdir successfully added."
 				else
-					echo "Failed to add submodule $subdir as $subdir_repo_public." >&2
+					echo "Failed to add submodule $subdir as $subdir_repo." >&2
 					break;
 				fi
 			done
