check if subdir exists in all branches are create empty subdir to ensure subdirectory-filter is happy (and does not resude to do anything)

diff --git a/scm/git-subdir2submodule b/scm/git-subdir2submodule
--- a/scm/git-subdir2submodule
+++ b/scm/git-subdir2submodule
@@ -218,6 +218,43 @@ function git_clone_and_shrink()
 	return $RES
 }
 
+function add_emtpy_directory()
+{
+    local repodir="$1"
+    local branch="$2"
+    local subdir="$3"
+    local RES=0
+
+    local subdir_git_dir=`mktemp -d "$repodir.XXXXXX"`
+    pushd "$subdir_git_dir" > /dev/null
+    git clone --single-branch -b "$branch" "$repodir" "$subdir_git_dir"; RES=$?
+    if [ $RES -eq 0 ]; then
+        git checkout "$branch"; RES=$?
+    else
+        echo "Failed to checkout $branch" >&2
+    fi
+    if [ $RES -eq 0 ]; then
+        mkdir -p "$subdir"
+        echo "empty file to start branch $branch" -> "$subdir/.empty"
+        git add "$subdir/.empty"; RES=$?
+    else
+        echo "Failed to add empty directory $subdir" >&2
+    fi
+    if [ $RES -eq 0 ]; then
+        git commit -m "Add empty directory for branch $branch" ; RES=$?
+    else
+        echo "Failed to commit changes" >&2
+    fi
+    if [ $RES -eq 0 ]; then
+        git push; RES=$?
+    else
+        echo "Failed to push changes to repository $repodir" >&2
+    fi
+    rm -rf "$subdir_git_dir"
+    popd > /dev/null
+    return $RES
+}
+
 function subdir_to_submodule()
 {
 	local repodir="$1"
@@ -227,18 +264,18 @@ function subdir_to_submodule()
 	if [ -d "$destdir" ]; then
 		if [ $force -eq 0 ]; then
 			if [ $keep -ne 0 ]; then
-				echo "Target directory already exists $destdir, but assume this is ok and just use it." >&2
+				echo "Target directory $destdir already exists, but assume this is ok and just use it." >&2
 				return 0
 			else
-				echo "Target directory already exists $destdir." >&2
+				echo "Target directory $destdir already exists." >&2
 				return 1
 			fi
 		else
-			echo "Target directory already exists $destdir. Remove it and continue" >&2
+			echo "Target directory $destdir already exists. Remove it and continue" >&2
 			rm -rf "$destdir"
 		fi
 	else
-		echo "Target directory does not exists $destdir." >&2
+		echo "Target directory $destdir does not exists." >&2
 	fi
 
     local start_time=`date +%s`
@@ -251,27 +288,18 @@ function subdir_to_submodule()
 	if [ $RES -eq 0 ]; then
         echo "Extract $subdir from $repodir to $subdir_git_dir"
         logmsg=`mktemp "$destdir.log.XXXXXX"`
-        git filter-branch --force --tag-name-filter cat --subdirectory-filter "$subdir" --prune-empty -- --all 2>&1 | tee "$logmsg"; RES=$?
-        msg_first_line=`cat "$logmsg" | head -n1`
-        #echo "GOt msg $msg_first_line"
-        if [ "$msg_first_line" == "Found nothing to rewrite" ]; then
-            echo "Filterbranch failed"
-            rm -rf "$subdir_git_dir"/*
-            git init
-            local commit_msg="extracted subdirectory $subdir from $repodir is empty"
-            echo "$commit_msg" > empty
-            git add empty
-            git commit -a -m "$commit_msg"
-#             verbose_exec git filter-branch --index-filter 'git rm -f --quiet --cached --ignore-unmatch *' -- --all; RES=$?
-#             if [ $RES -ne 0 ]; then
-#                 echo "Subdirectory successfully converted into $subdir_git_dir (was empty)."
-#             else
-#                 echo "Given directory does not exist in repository and clean all failed." >&2
-#             fi
-        else
-            RES=0
-        fi
-        rm -f "$logmsg"
+        local all_local_branches=`git branch`
+        # eliminate star marker
+        all_local_branches="${all_local_branches//\*/}"
+        for branch in $all_local_branches; do
+            local dir_list=`git ls-tree "$branch" "$subdir"`
+            if [ -z "$dir_list" ]; then
+                # directory does not exist in this branch
+                add_emtpy_directory "$subdir_git_dir" "$branch" "$subdir"; RES=$?
+            fi
+        done
+
+        git filter-branch --force --tag-name-filter cat --subdirectory-filter "$subdir" --prune-empty -- --all; RES=$?
 		end_time=`date +%s`
 		total_time=$(( $end_time - $start_time ))
 		if [ $RES -ne 0 ]; then
@@ -745,13 +773,22 @@ else
 				# get all branches except master (we add this special one in anyway)
 				all_branches=`git branch --all --no-abbrev --no-color --no-column`
 				all_remote_branches=`echo "$all_branches" | grep remotes | egrep -v '(HEAD|master)'`
+                all_local_branches='master'
 				for branch in $all_remote_branches; do
-					git branch --track ${branch##*/} $branch; RES=$?
-                    [ $RES -ne 0 ] && break
+                    local_branch_name="${branch##*/}"
+                    tmp=`git branch --list "$local_branch_name"`
+                    if [ -z "$tmp" ]; then
+                        echo "Creating local branch $local_branch_name tracking $branch"
+                        git branch --track "$local_branch_name" "$branch"; RES=$?
+                        [ $RES -ne 0 ] && break
+                    else
+                        echo "Local branch $local_branch_name already exists"
+                    fi
+                    all_local_branches="$all_local_branches ${branch##*/}"
 				done
 				
 				if [ $RES -eq 0 ]; then
-					all_selected_branches="$all_remote_branches master"
+					all_selected_branches="$all_local_branches"
 					if [ ! -z "$all_selected_branches" ]; then
 						for branch in $all_selected_branches; do
 							echo "Re-add submodules to branch $branch"
