add option to avoid adding and re-add the subdirs

diff --git a/scm/git-subdir2submodule b/scm/git-subdir2submodule
--- a/scm/git-subdir2submodule
+++ b/scm/git-subdir2submodule
@@ -13,6 +13,8 @@ subdir_list=''
 outdir=''
 force=0
 noop=0
+noadd=0
+readd=0
 bare='auto'
 config_file=''
 subdir_num=0
@@ -34,6 +36,8 @@ function usage()
     echo "    --newname <name>   name of the new GIT repository."
     echo "    --only-extract     only extract the subdirectories."
     echo "    --only-remove      only remove the subdirectories."
+    echo "    --noadd            do not re-add the removed subdirectories as submodules."
+    echo "    --readd            re-add the removed subdirectories as submodules."
     echo "    --shrink           only shrink the GIT repository."
     echo "    -o, --out <dir>    specifies the output directory"
     echo "    --file <path>      text file which contains the submodule specifications."
@@ -128,6 +132,7 @@ function git_clone_and_shrink()
 	local repodir="$1"
 	local destdir="$2"
     local clone_bare="$3"
+    local remove_empty_commits="$4"
 
 	pushd "$repodir" > /dev/null
 
@@ -142,7 +147,7 @@ function git_clone_and_shrink()
     end_time=`date +%s`
     total_time=$(( $end_time - $start_time ))
 	if [ $RES -eq 0 ]; then
-		git_shrink "$destdir" 1; RES=$?
+		git_shrink "$destdir" $remove_empty_commits; RES=$?
         end_time=`date +%s`
         total_time=$(( $end_time - $start_time ))
 		if [ $RES -eq 0 ]; then
@@ -235,7 +240,7 @@ function subdir_to_submodule()
 		if [ $clone_git_to_dest -ne 0 ]; then
 			# final cloning to reduce size
 			echo "Cloning $subdir_git_dir to $destdir"
-			git_clone_and_shrink "$subdir_git_dir" "$destdir" $clone_bare; RES=$?
+			git_clone_and_shrink "$subdir_git_dir" "$destdir" $clone_bare 0; RES=$?
 			end_time=`date +%s`
 			total_time=$(( $end_time - $start_time ))
 			if [ $RES -eq 0 ]; then
@@ -343,6 +348,8 @@ while [ $# -ne 0 ]; do
 		'--noop') noop=1; ;;
 		'--bare') bare=1; ;;
 		'--keep') keep=1; ;;
+        '--noadd') noadd=1; ;;
+        '--readd') readd=1; ;;
         '--newname') new_repo_name="$2"; shift; ;;
 		'-o'|'--out') outdir="$2"; shift; ;;
         '--only-extract') only_extract=1; ;;
@@ -540,7 +547,7 @@ elif [ $only_remove -ne 0 ]; then
     fi
     if [ $RES -eq 0 ]; then
         if [ "$temp_git_dir" != "$cloned_git_dir" ]; then
-            git_clone_and_shrink "$temp_git_dir" "$cloned_git_dir" $repo_is_bare; RES=$?
+            git_clone_and_shrink "$temp_git_dir" "$cloned_git_dir" $repo_is_bare 0; RES=$?
         else
             RES=0
         fi
@@ -557,16 +564,16 @@ elif [ $only_shrink -ne 0 ]; then
             RES=0
         else
             temp_git_dir=`mktemp -d "$cloned_git_dir.XXXXXX"`
-            git clone --no-hardlinks $bare_opt "$repo_git" "$temp_git_dir"; RES=$?
+            git clone $bare_opt "$repo_git" "$temp_git_dir"; RES=$?
         fi
     else
         temp_git_dir=`mktemp -d "$cloned_git_dir.XXXXXX"`
-        git clone --no-hardlinks $bare_opt "$repo_git" "$temp_git_dir"; RES=$?
+        git clone $bare_opt "$repo_git" "$temp_git_dir"; RES=$?
     fi
 
     if [ $RES -eq 0 ]; then
         if [ "$temp_git_dir" != "$cloned_git_dir" ]; then
-            git_clone_and_shrink "$temp_git_dir" "$cloned_git_dir" $repo_is_bare; RES=$?
+            git_clone_and_shrink "$temp_git_dir" "$cloned_git_dir" $repo_is_bare 0; RES=$?
         else
             RES=0
         fi
@@ -593,67 +600,84 @@ else
             RES=0
         else
             temp_git_dir=`mktemp -d "$cloned_git_dir.XXXXXX"`
-            git clone --no-hardlinks $bare_opt "$repo_git" "$temp_git_dir"; RES=$?
+            git clone $bare_opt "$repo_git" "$temp_git_dir"; RES=$?
         fi
     else
         temp_git_dir=`mktemp -d "$cloned_git_dir.XXXXXX"`
-        git clone --no-hardlinks $bare_opt "$repo_git" "$temp_git_dir"; RES=$?
+        git clone $bare_opt "$repo_git" "$temp_git_dir"; RES=$?
     fi
     if [ $RES -eq 0 ]; then
         # enter the cloned GIT repository
         pushd "$temp_git_dir" > /dev/null
 
-        # create extra GIT repositories for each subdir
-        for ((idx=0; idx < $subdir_num ; idx++)); do
-            subdir=${subdir_array[$idx]}
-            subdir_name=${subdir_name_array[$idx]}
-            subdir_repo=${subdir_repo_array[$idx]}
-
-            subdir_start_time=`date +%s`
-            subdir_to_submodule "$temp_git_dir" "$subdir" "$subdir_repo" "$bare"; RES=$?
-            subdir_end_time=`date +%s`
-            subdir_total_time=$(( $subdir_end_time - $subdir_start_time ))
-            if [ $RES -eq 0 ]; then
-                echo "GIT repository for $subdir successfully created ($subdir_total_time seconds)."
-            else
-                echo "Failed to convert subdirectory $subdir ($subdir_total_time seconds)." >&2
-                break;
-            fi
-        done
-        
-        if [ $RES -eq 0 ]; then
-            subdirs_to_remove=''
-            # remove the subdirs from the cloned GIT repository
-            # create a list of all objects (directories) to remove at once
+        if [ $readd -eq 0 ]; then
+            # create extra GIT repositories for each subdir
             for ((idx=0; idx < $subdir_num ; idx++)); do
                 subdir=${subdir_array[$idx]}
-                converted=${subdir_converted_array[$idx]}
-                
-                if [ $converted -ne 0 ]; then
-                    subdirs_to_remove="$subdirs_to_remove \"$subdir\""
-                else
-                    echo "Subdirectory $subdir already removed."
-                fi
-            done
+                subdir_name=${subdir_name_array[$idx]}
+                subdir_repo=${subdir_repo_array[$idx]}
 
-            if [ ! -z "$subdirs_to_remove" ]; then
                 subdir_start_time=`date +%s`
-                git filter-branch -f --tag-name-filter cat --index-filter "git rm -qrf --cached --ignore-unmatch $subdirs_to_remove" --prune-empty -- --all; RES=$?
+                subdir_to_submodule "$temp_git_dir" "$subdir" "$subdir_repo" "$bare"; RES=$?
                 subdir_end_time=`date +%s`
                 subdir_total_time=$(( $subdir_end_time - $subdir_start_time ))
                 if [ $RES -eq 0 ]; then
-                    echo "Subdirectories $subdirs_to_remove successfully removed ($subdir_total_time seconds)."
+                    echo "GIT repository for $subdir successfully created ($subdir_total_time seconds)."
                 else
-                    echo "Failed to remove subdirectories $subdirs_to_remove ($subdir_total_time seconds)." >&2
+                    echo "Failed to convert subdirectory $subdir ($subdir_total_time seconds)." >&2
+                    break;
+                fi
+            done
+            
+            if [ $RES -eq 0 ]; then
+                subdirs_to_remove=''
+                # remove the subdirs from the cloned GIT repository
+                # create a list of all objects (directories) to remove at once
+                for ((idx=0; idx < $subdir_num ; idx++)); do
+                    subdir=${subdir_array[$idx]}
+                    converted=${subdir_converted_array[$idx]}
+                    
+                    if [ $converted -ne 0 ]; then
+                        subdirs_to_remove="$subdirs_to_remove \"$subdir\""
+                    else
+                        echo "Subdirectory $subdir already removed."
+                    fi
+                done
+
+                if [ ! -z "$subdirs_to_remove" ]; then
+                    subdir_start_time=`date +%s`
+                    git filter-branch -f --tag-name-filter cat --index-filter "git rm -qrf --cached --ignore-unmatch $subdirs_to_remove" --prune-empty -- --all; RES=$?
+                    subdir_end_time=`date +%s`
+                    subdir_total_time=$(( $subdir_end_time - $subdir_start_time ))
+                    if [ $RES -eq 0 ]; then
+                        echo "Subdirectories $subdirs_to_remove successfully removed ($subdir_total_time seconds)."
+                    else
+                        echo "Failed to remove subdirectories $subdirs_to_remove ($subdir_total_time seconds)." >&2
+                    fi
                 fi
             fi
+        else
+            # just do the re-add; so nothing to do here
+            true
         fi
 
-		if [ $RES -eq 0 ]; then
+        if [ $RES -eq 0 ]; then
+            if [ $readd -ne 0 ]; then
+                do_readd=1
+            elif [ $noadd -eq 0 ]; then
+                do_readd=1
+            else
+                do_readd=0
+            fi
+        else
+            do_readd=0
+        fi
+
+		if [ $do_readd -ne 0 ]; then
 			# clone the repo again to re-add the directories as submodule again 
 			# for each branch
 			submodule_temp_git_dir=`mktemp -d "$cloned_git_dir.XXXXXX"`
-			git clone --no-hardlinks --no-checkout "$temp_git_dir" "$submodule_temp_git_dir"; RES=$?
+			git clone --no-checkout "$temp_git_dir" "$submodule_temp_git_dir"; RES=$?
 			if [ $RES -eq 0 ]; then
 				echo "Cloned $temp_git_dir into $submodule_temp_git_dir"
 				# enter the cloned GIT repository
@@ -748,7 +772,7 @@ else
                     repo_git_bak="$outdir/${repo_git_base}-org.git"
                     mv "$repo_git" "$repo_git_bak"
                 fi
-                git_clone_and_shrink "$temp_git_dir" "$cloned_git_dir" $bare; RES=$?
+                git_clone_and_shrink "$temp_git_dir" "$cloned_git_dir" $bare 0; RES=$?
             else
                 RES=0
             fi
