cleanup and re-add subdirs as modules

diff --git a/scm/git-subdir2submodule b/scm/git-subdir2submodule
--- a/scm/git-subdir2submodule
+++ b/scm/git-subdir2submodule
@@ -12,11 +12,10 @@ new_repo_name=''
 subdir_list=''
 outdir=''
 force=0
+noop=0
+bare='auto'
 config_file=''
 subdir_num=0
-submodule_init=0
-submodule_add=0
-submodule_add_origin=0
 keep=0
 declare -a subdir_array
 declare -a subdir_converted_array
@@ -30,14 +29,14 @@ function usage()
     echo "    -h, --help         shows this help screen"
     echo "    -v, --verbose      enable verbose output"
     echo "    -f, --force        override existing git repository. can be dangerous!"
+    echo "    --noop             do not actual perform the conversion, just print what would be done."
+    echo "    --bare             output repository should use bare format."
     echo "    --keep             keep temporary GIT repositories for troubleshooting."
-    echo "    --init             initialize submodules in main GIT repository."
-    echo "    --add              add submodules to main GIT repository."
     echo "    --newname <name>   name of the new GIT repository."
     echo "    --only-extract     only extract the subdirectories."
     echo "    --only-remove      only remove the subdirectories."
     echo "    --shrink           only shrink the GIT repository."
-    echo "    -o <dir>           specifies the output directory"
+    echo "    -o, --out <dir>    specifies the output directory"
     echo "    --file <path>      text file which contains the submodule specifications."
     exit 0
 }
@@ -71,6 +70,7 @@ function relative_path()
 function git_shrink()
 {
 	local repodir="$1"
+	local remove_empty_commits="$2"
 	
 	pushd "$repodir" > /dev/null
     local start_time=`date +%s`
@@ -84,10 +84,12 @@ function git_shrink()
 	fi
     
     if [ $RES -eq 0 ]; then
-        verbose_exec git filter-branch --prune-empty --tag-name-filter cat -- --all; RES=$?
-        if [ $RES -ne 0 ]; then
-            echo "Failed to prune empty commits from GIT repository $repodir" >&2
-        fi
+		if [ $remove_empty_commits -ne 0 ]; then
+			verbose_exec git filter-branch --prune-empty --tag-name-filter cat -- --all; RES=$?
+			if [ $RES -ne 0 ]; then
+				echo "Failed to prune empty commits from GIT repository $repodir" >&2
+			fi
+		fi
     fi
 
 	if [ $RES -eq 0 ]; then
@@ -141,7 +143,7 @@ function git_clone_and_shrink()
     end_time=`date +%s`
     total_time=$(( $end_time - $start_time ))
 	if [ $RES -eq 0 ]; then
-		git_shrink "$destdir"; RES=$?
+		git_shrink "$destdir" 1; RES=$?
         end_time=`date +%s`
         total_time=$(( $end_time - $start_time ))
 		if [ $RES -eq 0 ]; then
@@ -189,7 +191,8 @@ function subdir_to_submodule()
 	pushd "$subdir_git_dir" > /dev/null
 	git clone --no-hardlinks $bare_opt "$repodir" "$subdir_git_dir"; RES=$?
 	if [ $RES -eq 0 ]; then
-		git filter-branch --subdirectory-filter "$subdir" --prune-empty HEAD -- --all; RES=$?
+		git filter-branch -f --tag-name-filter cat --index-filter "git rm -qrf --cached --ignore-unmatch $subdir" --prune-empty -- --all; RES=$?
+		#git filter-branch --subdirectory-filter "$subdir" --prune-empty HEAD -- --all; RES=$?
 		if [ $RES -eq 0 ]; then
 			if [ $clone_bare -eq 0 ]; then
 				git reset --hard; RES=$?
@@ -198,7 +201,7 @@ function subdir_to_submodule()
 				fi
 			fi
 			if [ $RES -eq 0 ]; then
-				git_shrink "$subdir_git_dir"; RES=$?
+				git_shrink "$subdir_git_dir" 0; RES=$?
 				if [ $RES -eq 0 ]; then
 					echo "Subdirectory successfully converted into $subdir_git_dir."
 				else
@@ -262,7 +265,7 @@ function fully_remove_subdir()
     local total_time
 
 	#git filter-branch --tree-filter 'git rm -r -f --ignore-unmatch *.pyc' HEAD
-	git filter-branch -f --index-filter "git rm -qrf --cached --ignore-unmatch $subdirs" --prune-empty HEAD; RES=$?
+	git filter-branch -f --tag-name-filter cat --index-filter "git rm -qrf --cached --ignore-unmatch $subdirs" --prune-empty -- --all; RES=$?
 	if [ $RES -eq 0 ]; then
 		if [ -d "$repodir/.git/refs/original" ]; then
 			rm -rf "$repodir/.git/refs/original"
@@ -305,13 +308,15 @@ function add_submodule()
 	local submodule_repo="$3"
 	
 	pushd "$repodir" > /dev/null
+	
+	rel_path=$(relative_path $repodir $path)
 
-	git submodule add --force "$submodule_repo" "$path"; RES=$?
+	git submodule add --force "$submodule_repo" "$rel_path"; RES=$?
 	if [ $RES -eq 0 ]; then
 		# stash the modified .gitmodules
 		git add "${repodir}/.gitmodules"; RES=$?
 		if [ $RES -eq 0 ]; then
-			echo "Submodule $submodule_repo as $path successfully added."
+			echo "Submodule $submodule_repo as $rel_path successfully added."
 		else
 			echo "Failed to add ${repodir}/.gitmodules" >&2
 		fi
@@ -329,11 +334,11 @@ while [ $# -ne 0 ]; do
 		'-?'|'-h'|'--help') usage;;
 		'-v'|'--verbose') verbose=1; ;;
 		'-f'|'--force') force=1; ;;
+		'--noop') noop=1; ;;
+		'--bare') bare=1; ;;
 		'--keep') keep=1; ;;
-		'--add') submodule_add=1; ;;
-		'--init') submodule_add=1; submodule_init=1; ;;
         '--newname') new_repo_name="$2"; shift; ;;
-		'-o') outdir="$2"; shift; ;;
+		'-o'|'--out') outdir="$2"; shift; ;;
         '--only-extract') only_extract=1; ;;
         '--only-remove') only_remove=1; ;;
         '--shrink') only_shrink=1; ;;
@@ -375,7 +380,15 @@ else
     [ -d "$repo_git/.git" ] && repo_is_bare=0 || repo_is_bare=1
 fi
 
-[ -z "$outdir" ] && outdir=`readlink -f $(pwd)`
+[ "$bare" == 'auto' ] && bare=$repo_is_bare
+
+[ -z "$outdir" ] && outdir=`readlink -f $(pwd)` || outdir=`readlink -f "$outdir"`
+
+if [ -z "$new_repo_name" ]; then
+    repo_name=`basename "$repo_git" '.git'`
+else
+    repo_name="$new_repo_name"
+fi
 
 if [ -z "$config_file" ]; then
     subdir_config_file=`mktemp`
@@ -396,7 +409,11 @@ if [ ! -z "$subdir_config_file" ]; then
 
 		[ ${#fields[*]} -gt 1 ] && subdir_name="${fields[1]}" || subdir_name="$subdir_safe"
 		subdir_name_safe=${subdir_name//\//_}
-		[ $clone_bare -ne 0 ] && subdir_git_dir="$outdir/${subdir_name_safe}.git" || subdir_git_dir="$outdir/${subdir_name_safe}"
+		if [ $bare -ne 0 ]; then
+			subdir_git_dir="$outdir/${repo_name}-${subdir_name_safe}.git"
+		else
+			subdir_git_dir="$outdir/${repo_name}-${subdir_name_safe}"
+		fi
 		#echo "subdir_git_dir=$subdir_git_dir"
 
 		[ ${#fields[*]} -gt 2 ] && subdir_repo_public="${fields[2]}" || subdir_repo_public="$subdir_git_dir"
@@ -414,12 +431,11 @@ if [ -z "$config_file" ]; then
     rm -f "$subdir_config_file"
 fi
 
-if [ -z "$new_repo_name" ]; then
-    repo_name=`basename "$repo_git" '.git'`
+if [ $bare -ne 0 ]; then
+	cloned_git_dir="$outdir/${repo_name}.git"
 else
-    repo_name="$new_repo_name"
+	cloned_git_dir="$outdir/${repo_name}"
 fi
-cloned_git_dir="$outdir/${repo_name}.git"
 #if [ "$cloned_git_dir" == "$repo_git" ]; then
 #    cloned_git_dir="$outdir/${repo_name}-new.git"
 #fi
@@ -450,10 +466,8 @@ for ((idx=0; idx < $subdir_num ; idx++)); do
     fi
 done
 
-if [ $submodule_add -eq 0 ]; then
-	[ $clone_bare -ne 0 ] && bare_opt='--bare' || bare_opt=''
-else
-	bare_opt=''
+if [ $noop -ne 0 ]; then
+	exit 0
 fi
 
 if [ $only_extract -ne 0 ]; then
@@ -568,6 +582,8 @@ else
         exit 1
     fi
 
+	[ $bare -ne 0 ] && bare_opt='--bare' || bare_opt=''
+
     if [ $keep -ne 0 ]; then
         if [ -d "$cloned_git_dir" ]; then
             temp_git_dir="$cloned_git_dir"
@@ -605,6 +621,7 @@ else
         if [ $RES -eq 0 ]; then
             subdirs_to_remove=''
             # remove the subdirs from the cloned GIT repository
+            # create a list of all objects (directories) to remove at once
             for ((idx=0; idx < $subdir_num ; idx++)); do
                 subdir=${subdir_array[$idx]}
                 converted=${subdir_converted_array[$idx]}
@@ -615,10 +632,10 @@ else
                     echo "Subdirectory $subdir already removed."
                 fi
             done
-            
+
             if [ ! -z "$subdirs_to_remove" ]; then
                 subdir_start_time=`date +%s`
-                fully_remove_subdir "$temp_git_dir" $subdirs_to_remove; RES=$?
+                git filter-branch -f --tag-name-filter cat --index-filter "git rm -qrf --cached --ignore-unmatch $subdirs_to_remove" --prune-empty -- --all; RES=$?
                 subdir_end_time=`date +%s`
                 subdir_total_time=$(( $subdir_end_time - $subdir_start_time ))
                 if [ $RES -eq 0 ]; then
@@ -629,68 +646,97 @@ else
             fi
         fi
 
-        if [ $submodule_add -ne 0 ]; then
-            if [ $RES -eq 0 ]; then
-                # re-add the subdirs as submodules from the cloned GIT repository
-                for ((idx=0; idx < $subdir_num ; idx++)); do
-                    subdir=${subdir_array[$idx]}
-                    subdir_name=${subdir_name_array[$idx]}
-                    subdir_repo=${subdir_repo_array[$idx]}
+		if [ $RES -eq 0 ]; then
+			# clone the repo again to re-add the directories as submodule again 
+			# for each branch
+			submodule_temp_git_dir=`mktemp -d "$cloned_git_dir.XXXXXX"`
+			git clone --no-hardlinks --no-checkout "$temp_git_dir" "$submodule_temp_git_dir"; RES=$?
+			if [ $RES -eq 0 ]; then
+				echo "Cloned $temp_git_dir into $submodule_temp_git_dir"
+				# enter the cloned GIT repository
+				pushd "$submodule_temp_git_dir" > /dev/null
 
-					rel_path=$(relative_path $cloned_git_dir $subdir_repo)
+				# get all branches except master (we add this special one in anyway)
+				all_branches=`git branch --all --no-abbrev --no-color --no-column`
+				all_remote_branches=`echo "$all_branches" | grep remotes | egrep -v '(HEAD|master)'`
+				for branch in $all_remote_branches; do
+					git branch --track ${branch##*/} $branch; RES=?
+				done
+				
+				if [ $RES -eq 0 ]; then
+					all_selected_branches="$all_remote_branches master"
+					if [ ! -z "$all_selected_branches" ]; then
+						for branch in $all_selected_branches; do
+							echo "Re-add submodules to branch $branch"
+							git checkout $branch; RES=$?
+							if [ $RES -eq 0 ]; then
+								echo "Initailize existing submodules"
+								# update and initialize existing submodule
+								#git submodule update --init; RES=$?
+								if [ $RES -eq 0 ]; then
+									# prepare a commit message
+									commit_msg_file=`mktemp`
+									echo "$script_name converted the following subdirectories into submodules:" >> "$commit_msg_file"
+									
+									# re-add the subdirs as submodules from the cloned GIT repository
+									for ((idx=0; idx < $subdir_num ; idx++)); do
+										subdir=${subdir_array[$idx]}
+										subdir_name=${subdir_name_array[$idx]}
+										subdir_repo=${subdir_repo_array[$idx]}
+										rel_path=$(relative_path $temp_git_dir $subdir_repo)
+										echo "  $subdir -> $rel_path" >> "$commit_msg_file"
+										echo "Add subdir $subdir as $rel_path"
+										git submodule add -b "$branch" --force "$rel_path" "$subdir"; RES=$?
+										if [ $RES -eq 0 ]; then
+											echo "Submodule $subdir successfully added."
+										else
+											echo "Failed to add submodule $subdir as $subdir_repo." >&2
+											break;
+										fi
+									done
+									if [ $RES -eq 0 ]; then
+										echo "Add .gitmodules files"
+										git add .gitmodules; RES=$?
+										echo "Commit submodule changes on branch $branch"
+										git commit -F "$commit_msg_file"; RES=$?
+										rm "$commit_msg_file"
+										if [ $RES -eq 0 ]; then
+											echo "Submodule modifications commited."
+										else
+											echo "Failed to commit submodule modifications." >&2
+										fi
+									else
+										echo "Failed to update submodules." >&2
+									fi
+								fi
+							else
+								echo "Failed to checkout branch $branch in $submodule_temp_git_dir." >&2
+							fi
+						done
+						if [ $RES -eq 0 ]; then
+							echo "Push submodule changes back to $temp_git_dir."
+							git push --all; RES=$?
+							if [ $RES -eq 0 ]; then
+								echo "All submodules are re-added and pushed to $temp_git_dir."
+							else
+								echo "Push submodule changes to $temp_git_dir." >&2
+							fi
+						fi
+					else
+						echo "Failed to set up remote branches in $submodule_temp_git_dir." >&2
+					fi
+				fi
+				# leave the cloned GIT repository for submodule re-add
+				popd > /dev/null
+				rm -rf "$submodule_temp_git_dir"
+			else
+				echo "Failed to clone $temp_git_dir into $submodule_temp_git_dir." >&2
+			fi
+		fi
 
-                    add_submodule "$temp_git_dir" "$subdir" "$rel_path"; RES=$?
-                    if [ $RES -eq 0 ]; then
-                        echo "Submodule $subdir successfully added."
-                    else
-                        echo "Failed to add submodule $subdir as $subdir_repo." >&2
-                        break;
-                    fi
-                done
-            fi
-        fi
-
-        if [ $submodule_init -ne 0 ]; then
-            if [ $RES -eq 0 ]; then
-                git submodule init; RES=$?
-                if [ $RES -eq 0 ]; then
-                    git submodule update; RES=$?
-                    if [ $RES -eq 0 ]; then
-                        echo "New submodules initialized and updated successfully."
-                    else
-                        echo "Failed to update submodules." >&2
-                    fi
-                else
-                    echo "Failed to initialize submodules." >&2
-                fi
-            fi
-        fi
-
-        if [ $submodule_add -ne 0 ]; then
-            if [ $RES -eq 0 ]; then
-                commit_msg_file=`mktemp`
-                echo "$script_name converted the following subdirectories into submodules:" >> "$commit_msg_file"
-                for ((idx=0; idx < $subdir_num ; idx++)); do
-                    subdir=${subdir_array[$idx]}
-                    subdir_name=${subdir_name_array[$idx]}
-                    subdir_repo_public=${subdir_repo_public_array[$idx]}
-                    echo "  $subdir -> $subdir_repo_public" >> "$commit_msg_file"
-                done
-                git commit -F "$commit_msg_file"; RES=$?
-                rm "$commit_msg_file"
-                if [ $RES -eq 0 ]; then
-                    echo "Submodule modifications commited."
-                else
-                    echo "Failed to commit submodule modifications." >&2
-                fi
-            else
-                echo "Failed to update submodules." >&2
-            fi
-        fi
-        
         # leave the cloned GIT repository
         popd > /dev/null
-        
+
         if [ $RES -eq 0 ]; then
             if [ "$temp_git_dir" != "$cloned_git_dir" ]; then
                 if [ "$repo_git" == "$cloned_git_dir" ]; then
@@ -698,7 +744,7 @@ else
                     repo_git_bak="$outdir/${repo_git_base}-org.git"
                     mv "$repo_git" "$repo_git_bak"
                 fi
-                git_clone_and_shrink "$temp_git_dir" "$cloned_git_dir" $repo_is_bare; RES=$?
+                git_clone_and_shrink "$temp_git_dir" "$cloned_git_dir" $bare; RES=$?
             else
                 RES=0
             fi
