report success when selected directory does not exist

diff --git a/scm/git-subdir2submodule b/scm/git-subdir2submodule
--- a/scm/git-subdir2submodule
+++ b/scm/git-subdir2submodule
@@ -192,7 +192,21 @@ function subdir_to_submodule()
 	pushd "$subdir_git_dir" > /dev/null
 	git clone --no-hardlinks $bare_opt "$repodir" "$subdir_git_dir"; RES=$?
 	if [ $RES -eq 0 ]; then
-		git filter-branch -f --subdirectory-filter "$subdir" --prune-empty -- --all; RES=$?
+        echo "Extract $subdir from $repodir to $subdir_git_dir"
+        logmsg=`mktemp "$destdir.log.XXXXXX"`
+        verbose_exec git filter-branch --force --subdirectory-filter "$subdir" --prune-empty -- --all 2>&1 | tee "$logmsg"; RES=$?
+        if [ $RES -ne 0 ]; then
+            msg_first_line=`cat "$logmsg" | head -n1`
+            if [ "$msg_first_line" == "Found nothing to rewrite" ]; then
+                echo "Subdirectory successfully converted into $subdir_git_dir (was empty)." | tee -a "$LOGFILE"
+                RES=0
+            fi
+         elif [ $RES -eq 0 ]; then
+            true
+        else
+            echo "Filter branch to GIT repository $subdir_git_dir failed with $RES ($total_time seconds)" >&2
+        fi
+        rm -f "$logmsg"
 		end_time=`date +%s`
 		total_time=$(( $end_time - $start_time ))
 		if [ $RES -ne 0 ]; then
