try to shrink down repos

diff --git a/scm/git-subdir2submodule b/scm/git-subdir2submodule
--- a/scm/git-subdir2submodule
+++ b/scm/git-subdir2submodule
@@ -11,8 +11,11 @@ force=0
 config_file=''
 subdir_num=0
 submodule_init=0
+submodule_add=0
+submodule_add_origin=0
 keep=0
 declare -a subdir_array
+declare -a subdir_converted_array
 declare -a subdir_name_array
 declare -a subdir_repo_array
 declare -a subdir_repo_public_array
@@ -24,6 +27,8 @@ function usage()
     echo "    -v, --verbose      enable verbose output"
     echo "    -f, --force        override existing git repository. can be dangerous!"
     echo "    --keep             keep temporary GIT repositories for troubleshooting."
+    echo "    --init             initialize submodules in main GIT repository."
+    echo "    --add              add submodules to main GIT repository."
     echo "    -o <dir>           specifies the output directory"
     echo "    -s <base_url>      override the base url for submodules."
     echo "    --file <path>      text file which contains the submodule specifications."
@@ -60,6 +65,8 @@ function subdir_to_submodule()
 			echo "Target directory already exists $destdir. Remove it and continue" >&2
 			rm -rf "$destdir"
 		fi
+	else
+		echo "Target directory does not exists $destdir." >&2
 	fi
 
 	[ $clone_bare -ne 0 ] && bare_opt='--bare' || bare_opt=''
@@ -80,11 +87,15 @@ function subdir_to_submodule()
 					if [ $RES -eq 0 ]; then
 						git remote rm origin; RES=$?
 						if [ $RES -eq 0 ]; then
-							git remote add origin "$public_url"; RES=$?
-							if [ $RES -eq 0 ]; then
-								echo "Subdirectory successfully converted into $subdir_git_dir."
+							if [ $submodule_add_origin -ne 0 ]; then
+								git remote add origin "$public_url"; RES=$?
+								if [ $RES -eq 0 ]; then
+									echo "Subdirectory successfully converted into $subdir_git_dir."
+								else
+									echo "Failed to add remote origin $public_url for GIT repository $subdir_git_dir." >&2
+								fi
 							else
-								echo "Failed to add remote origin $public_url for GIT repository $subdir_git_dir." >&2
+								echo "Subdirectory successfully converted into $subdir_git_dir."
 							fi
 						else
 							echo "Failed to remove remote origin from GIT repository $subdir_git_dir." >&2
@@ -108,11 +119,24 @@ function subdir_to_submodule()
 	popd > /dev/null
 	
 	if [ $RES -eq 0 ]; then
-		mv "$subdir_git_dir" "$destdir"; RES=$?
-	else
-		# remove the temporary clone of GIT repo
-		rm -rf "$repo_git_full"
+		for ((idx=0; idx < $subdir_num ; idx++)); do
+			current_subdir=${subdir_array[$idx]}
+			if [ "$subdir" == "$current_subdir" ]; then
+				subdir_converted_array[$idx]=1
+				break
+			fi
+		done
+
+		# final cloning to reduce size
+		git clone --no-hardlinks $bare_opt "$subdir_git_dir" "$destdir"; RES=$?
+		if [ $RES -eq 0 ]; then
+			echo "Subdirectory cloned from $subdir_git_dir to $destdir"
+		else
+			echo "Final cloning the GIT repository $subdir_git_dir failed." >&2
+		fi
 	fi
+	# remove the temporary clone of GIT repo
+	rm -rf "$repo_git_full"
 	return $RES
 }
 
@@ -181,9 +205,15 @@ while [ $# -ne 0 ]; do
 		'-v'|'--verbose') verbose=1; ;;
 		'-f'|'--force') force=1; ;;
 		'--keep') keep=1; ;;
+		'--add') submodule_add=1; ;;
+		'--init') submodule_add=1; submodule_init=1; ;;
 		'-o') outdir="$2"; shift; ;;
 		'-s') submodule_base_url="$2"; shift; ;;
 		'--file') config_file="$2"; shift; ;;
+		-*)
+			echo "Invalid option $1 specified." >&2
+			exit 1
+			;;
         *)
 			if [ -z "$repo_git" ]; then
 				repo_git="$1"
@@ -240,6 +270,7 @@ if [ ! -z "$config_file" ]; then
 		subdir_git_dir="$outdir/${subdir_safe}.git"
 
 		subdir_array[$subdir_num]="$subdir"
+		subdir_converted_array[$subdir_num]=0
 		subdir_name_array[$subdir_num]="$subdir_name"
 		subdir_repo_array[$subdir_num]="$subdir_git_dir"
 		subdir_repo_public_array[$subdir_num]="$subdir_repo_public"
@@ -261,6 +292,7 @@ else
 			subdir_git_dir="$outdir/${subdir_safe}.git"
 		
 			subdir_array[$subdir_num]="$subdir"
+			subdir_converted_array[$subdir_num]=0
 			subdir_name_array[$subdir_num]="$subdir_safe"
 			subdir_repo_array[$subdir_num]="$subdir_git_dir"
 			subdir_repo_public_array[$subdir_num]="$subdir_git_dir"
@@ -292,17 +324,23 @@ if [ $verbose -ne 0 ]; then
 fi
 
 cloned_git_dir="$outdir/${repo_name}.git"
+if [ $submodule_add -eq 0 ]; then
+	[ $clone_bare -ne 0 ] && bare_opt='--bare' || bare_opt=''
+else
+	bare_opt=''
+fi
 
 if [ $keep -ne 0 ]; then
 	if [ -d "$cloned_git_dir" ]; then
 		temp_git_dir="$cloned_git_dir"
+		RES=0
 	else
 		temp_git_dir=`mktemp -d "$cloned_git_dir.XXXXXX"`
-		git clone --no-hardlinks "$repo_git" "$temp_git_dir"; RES=$?
+		git clone --no-hardlinks $bare_opt "$repo_git" "$temp_git_dir"; RES=$?
 	fi
 else
 	temp_git_dir=`mktemp -d "$cloned_git_dir.XXXXXX"`
-	git clone --no-hardlinks "$repo_git" "$temp_git_dir"; RES=$?
+	git clone --no-hardlinks $bare_opt "$repo_git" "$temp_git_dir"; RES=$?
 fi
 if [ $RES -eq 0 ]; then
 	# enter the cloned GIT repository
@@ -328,34 +366,41 @@ if [ $RES -eq 0 ]; then
 		# remove the subdirs from the cloned GIT repository
 		for ((idx=0; idx < $subdir_num ; idx++)); do
 			subdir=${subdir_array[$idx]}
-
-			fully_remove_subdir "$temp_git_dir" "$subdir"; RES=$?
-			if [ $RES -eq 0 ]; then
-				echo "Subdirectory $subdir successfully removed."
+			converted=${subdir_converted_array[$idx]}
+			
+			if [ $converted -ne 0 ]; then
+				fully_remove_subdir "$temp_git_dir" "$subdir"; RES=$?
+				if [ $RES -eq 0 ]; then
+					echo "Subdirectory $subdir successfully removed."
+				else
+					echo "Failed to convert subdirectory $subdir." >&2
+					break;
+				fi
 			else
-				echo "Failed to convert subdirectory $subdir." >&2
-				break;
+				echo "Subdirectory $subdir already removed."
 			fi
 		done
 	fi
 
-	if [ $RES -eq 0 ]; then
-		# re-add the subdirs as submodules from the cloned GIT repository
-		for ((idx=0; idx < $subdir_num ; idx++)); do
-			subdir=${subdir_array[$idx]}
-			subdir_name=${subdir_name_array[$idx]}
-			subdir_repo_public=${subdir_repo_public_array[$idx]}
+	if [ $submodule_add -ne 0 ]; then
+		if [ $RES -eq 0 ]; then
+			# re-add the subdirs as submodules from the cloned GIT repository
+			for ((idx=0; idx < $subdir_num ; idx++)); do
+				subdir=${subdir_array[$idx]}
+				subdir_name=${subdir_name_array[$idx]}
+				subdir_repo_public=${subdir_repo_public_array[$idx]}
 
-			add_submodule "$temp_git_dir" "$subdir" "$subdir_repo_public"; RES=$?
-			if [ $RES -eq 0 ]; then
-				echo "Submodule $subdir successfully added."
-			else
-				echo "Failed to add submodule $subdir as $subdir_repo_public." >&2
-				break;
-			fi
-		done
+				add_submodule "$temp_git_dir" "$subdir" "$subdir_repo_public"; RES=$?
+				if [ $RES -eq 0 ]; then
+					echo "Submodule $subdir successfully added."
+				else
+					echo "Failed to add submodule $subdir as $subdir_repo_public." >&2
+					break;
+				fi
+			done
+		fi
 	fi
-	
+
 	if [ $submodule_init -ne 0 ]; then
 		if [ $RES -eq 0 ]; then
 			git submodule init; RES=$?
@@ -372,26 +417,28 @@ if [ $RES -eq 0 ]; then
 		fi
 	fi
 
-	if [ $RES -eq 0 ]; then
-		commit_msg_file=`mktemp`
-		echo "$script_name converted the following subdirectories into submodules:" >> "$commit_msg_file"
-		for ((idx=0; idx < $subdir_num ; idx++)); do
-			subdir=${subdir_array[$idx]}
-			subdir_name=${subdir_name_array[$idx]}
-			subdir_repo_public=${subdir_repo_public_array[$idx]}
-			echo "  $subdir -> $subdir_repo_public" >> "$commit_msg_file"
-		done
-		git commit -F "$commit_msg_file"; RES=$?
-		rm "$commit_msg_file"
+	if [ $submodule_add -ne 0 ]; then
 		if [ $RES -eq 0 ]; then
-			echo "Submodule modifications commited."
+			commit_msg_file=`mktemp`
+			echo "$script_name converted the following subdirectories into submodules:" >> "$commit_msg_file"
+			for ((idx=0; idx < $subdir_num ; idx++)); do
+				subdir=${subdir_array[$idx]}
+				subdir_name=${subdir_name_array[$idx]}
+				subdir_repo_public=${subdir_repo_public_array[$idx]}
+				echo "  $subdir -> $subdir_repo_public" >> "$commit_msg_file"
+			done
+			git commit -F "$commit_msg_file"; RES=$?
+			rm "$commit_msg_file"
+			if [ $RES -eq 0 ]; then
+				echo "Submodule modifications commited."
+			else
+				echo "Failed to commit submodule modifications." >&2
+			fi
 		else
-			echo "Failed to commit submodule modifications." >&2
+			echo "Failed to update submodules." >&2
 		fi
-	else
-		echo "Failed to update submodules." >&2
 	fi
-
+	
 	# leave the cloned GIT repository
 	popd > /dev/null
 	
